apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::598128533809:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::598128533809:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8L2P2VRDYZ3D
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-10T21:05:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1529"
  uid: d80b4099-7035-41b6-9493-9d24bfbc0575
